### ISSUE TITLE
Simulate DynamoDB Locally

### ISSUE THREAD

**Issue by johncmckim** [gertjvr/serverless-plugin-simulate#28]
# This is a Feature Proposal

## Description
Support DynamoDB through [dynalite](https://github.com/mhart/dynalite) or [dynamodb local](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html)

I'm leaning towards dynalite as it would be easy to integrate.

It would be important to inject a `SERVERLESS_SIMULATE_DYNAMODB_ENDPOINT` environment variable into the container

**Comment by hassankhan** [comment]
It might also be an idea to allow seeding the DynamoDB tables as well, not sure if dynalite has a mechanism for that. I must confess, my Docker knowledge is 💩  so not sure if I can help with a PR 😞

**Comment by nicka** [comment]
We're using dynalite for the most, dynamodb local gave us some issues in CI.

**Comment by nicka** [comment]
Do you already have some ideas around implementation? For example are you thinking about parsing `serverless.yml:Resources` in order to find `DynamoDB::Table` resources? Would love to help out with this.

**Comment by johncmckim** [comment]
@nicka would love some help. I was definitely thinking of finding Tables in `serverless.yml` and creating them in dynalite automatically.

An important implementation consideration is that this should support a scenario where developers are trying to test multiple serverless services. The plugin currently supports this by separating Lambda & API Gateway. When you start the API Gateway simulation, it registers functions with the Lambda service.

Similarly, we need a way for the plugin to create tables with a DynamoDB local service. There's a few considerations in terms of developer experience. There's a few options I can thinking of

1. Registration command.
A new command to register local resources like dynamodb or kinesis .
i.e. `sls simulate register-resources --dynamodb-port xxxx`

2. Hook into `apigateway` command
When the users executes `sls simulate apigateway --lambda-port xxx  --dynamodb-port xxxx` create dynamodb tables during startup.

3. A new command that does everything
`sls simulate start --lambda-port xxx --dynamodb-port xxx --kinesis-port xxxx`

The other consideration is that the Lambda service inject the DynamoDB endpoint into the environment to allow functions to access this. One option is to create those variables during function registration. So each function could in theory use a different DynamoDB endpoint if required.

The UX of this is really important so I'm keen to hear your thoughts. Happy to make breaking changes now to get this right.

**Comment by gertjvr** [comment]
We currenly use the dynamodb local combined with a docker image, we could easily just run up a new docker image based on the resource you need, similar with any moto[server] services.

docker-compose
```
version: '2'

services:
  dynamo:
    image: tray/dynamodb-local
    ports:
      - "7777:7777"
    command: -port 7777 -inMemory -sharedDb
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
```

**Comment by hassankhan** [comment]
IMO it'd be nice to have the plugin configuration under `custom` in the `serverless.yml`. That way I can move any configuration out to an external file and reference it instead:

```
custom:
  simulate: 
    services:
      - apigateway:
          ports: 5000:4000
      - dynamodb:
          port: 6000:4000
          tables: 
            - table1
            - table2
            - table3
          seeds: "./seeds/runAll.js"
```

**Comment by gertjvr** [comment]
I can see everyone going to ask to simulate there favorite solution, rather than recreate docker-compose inside the the serviceless.yml

Options
- maybe we need to add a feature to allow for a script to be executed before startup at minimum.
- reference a docker-compose.yaml
- use simulate configuration and if simple start the docker container, else construct a docker-compose.yml.

option 1
```yaml
custom:
    simulate: 'startup.js'
```

option 2
```yaml
custom:
    simulate: 'docker-compose.yaml'
```

option 3
```yaml
custom:
    simulate: 
        build: moto
        ports:
          - "5000:5000"
        environments:
        networks:
        ...
```

**Comment by hassankhan** [comment]
Options 2 and 3 can kinda sorta be merged with [Serverless' own variables mechanism](https://serverless.com/framework/docs/providers/aws/guide/variables#reference-variables-in-other-files):

```
custom:
  simulate: ${file(./docker-compose.yml)}
```

**Comment by gertjvr** [comment]
@hassankhan I am award that that its possible to do that, but you missed the point, the custom simulate config reference is there to either run a docker container, run docker-compose or generate a docker-compose file to run before the plugin starts.

**Comment by gertjvr** [comment]
Resolved with #37

**Comment by yoyeung** [comment]
Sorry guy. I setup the s3 to try access from my lambda.
the problems i don't know the endpoint for my s3 service. docker said it's localhost:8000
How can i do it? i dont have much experience on docker.

Thanks

**Comment by gertjvr** [comment]
@yoyeung can you upload your `docker-compose.yml` file.

**Comment by yoyeung** [comment]
@gertjvr 
actually it's same as the example one.
```
version: '2'

services:
  s3:
    build: images/moto
    hostname: s3
    command: [s3, "-H", "0.0.0.0"]
    ports:
      - "8000:5000"
```

and the container ip is localhost:8000
<img width="752" alt="screen shot 2017-03-16 at 8 59 05 am" src="https://cloud.githubusercontent.com/assets/451538/23977082/e17d6e64-0a26-11e7-956b-e8a1a2e7a5a9.png">
if i using Virutal box i can get the ip, but using native docker i cannot.
