### ISSUE TITLE
Add support for path: '{proxy+}'

### ISSUE THREAD

**Issue by nicka** [gertjvr/serverless-plugin-simulate#32]
# This is a Feature Proposal

## Description

Would love to have support for APIGW's `'{proxy+}'`.

```yml
events:
- http:
     path: '{proxy+}'
     method: any
```
