### ISSUE TITLE
Simulated API Gateway incorrectly routes requests to similar paths

### ISSUE THREAD

**Issue by rlgod** [gertjvr/serverless-plugin-simulate#40]
# This is a Bug Report

## Description

For bug reports:
* As an example, the request `PUT /forum/answer/correct` is incorrectly routing to the function for the path `PUT /forum/answer` because of regex matching issues.
* The correct url path should be matched
* serverless.yml snippet
```
  answerUpdate:
    handler: src/index.answerUpdate
    memorySize: ${self:custom.FUNCTION_MEMORY}
    timeout: ${self:custom.FUNCTION_TIMEOUT}
    events:
      - http:
          integration: lambda
          path: forum/answer
          method: put
          cors: true
          authorizer: authorizer

  answerCorrect:
    handler: src/index.answerCorrect
    memorySize: ${self:custom.FUNCTION_MEMORY}
    timeout: ${self:custom.FUNCTION_TIMEOUT}
    events:
      - http:
          integration: lambda
          path: forum/answer/correct
          method: put
          cors: true
          authorizer: authorizer
```

* Console output showing the issue
```
Serverless: Processing statement {"Action":"execute-api:Invoke","Effect":"Allow","Resource":["arn:aws:execute-api:us-east-1:<Account id>:<API id>/dev/*/*"]}
Serverless: Checking resources ["arn:aws:execute-api:us-east-1:<Account id>:<API id>/dev/*/*"] for match
Serverless: Finding a match for path /forum/answer/correct
Serverless: Creating event
Serverless: Invoking answerUpdate
Serverless: Invoking function src/index.answerUpdate
```

## Additional Data

* ***Serverless Framework Version you're using***: 1.6.1
* ***Operating System***: OSX
* ***Stack Trace***: None
* ***Provider Error messages***: None
