### ISSUE TITLE
CORS broken for endpoints with the same path but different HTTP method

### ISSUE THREAD

**Issue by rlgod** [gertjvr/serverless-plugin-simulate#42]
# This is a Bug Report

## Description

For bug reports:
* Preflight requests only return allowed methods for `OPTIONS` and the method of the first function in the serverless.yml with a given route **BUT NOT ANY AFTER THAT**
* If I have three functions with the following http events
    1. `POST /mypath`
    2. `PUT /mypath`
    3. `GET /mypath`
    Then the request `OPTIONS /mypath` should return this header `Access-Control-Allow-Methods: OPTIONS, GET, POST, PUT`

* An example config which causes this bug to occur would be
```
Functions:
  questionSubmit:
    handler: src/index.questionCreate
    events:
      - http:
          integration: lambda
          path: forum/question
          method: post
          cors: true

  questionUpdate:
    handler: src/index.questionUpdate
    events:
      - http:
          integration: lambda
          path: forum/question
          method: put
          cors: true
```
